### ISSUE TITLE
Error en  Window Utils  when get variables

### ISSUE THREAD

**Issue by salinashf** [Macro-Deck-org/Macro-Deck#254]
** Name of the plugin **
Window Utils

** Version **
1.4.0

When trying to read a variable, an example error is generated Button Add Variable
Log 
22:39:58 [Macro Deck] [Info] >> Starting websocket server @ 192.190.0.153:8088
22:39:58 [Macro Deck] [Info] >> Starting USB websocket server @ 127.0.0.1:8088
22:39:58 [Macro Deck] [Info] >> Macro Deck started successfully
22:39:58 [Macro Deck] [Info] >> MacroDeckPipeServer: Initializing pipe server
22:39:58 [Macro Deck] [Info] >> MacroDeckPipeServer: Initializing pipe server complete
22:39:58 [Macro Deck] [Info] >> Macro Deck startup finished (took 1555ms)
22:40:43 [Macro Deck] [Error] >> MacroDeck: ApplicationThreadException: Field not found: 'SuchByte.MacroDeck.Variables.VariableManager.Variables'.
   at SuchByte.WindowsUtils.GUI.TextSelector.BtnAddVariable_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
22:40:56 [Macro Deck] [Error] >> MacroDeck: ApplicationThreadException: Field not found: 'SuchByte.MacroDeck.Variables.VariableManager.Variables'.
   at SuchByte.WindowsUtils.GUI.TextSelector.BtnAddVariable_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by salinashf** [comment]
# this is   complete   log #

22:39:57 [Macro Deck] [Info] >> Loading language files...
22:39:57 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Chinese.json...
22:39:57 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Dutch.json...
22:39:57 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.English.json...
22:39:57 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Filipino.json...
22:39:57 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Finnish.json...
22:39:57 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.French.json...
22:39:57 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.German.json...
22:39:57 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Hungarian.json...
22:39:57 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Italian.json...
22:39:57 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Japanese.json...
22:39:57 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Korean.json...
22:39:57 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Polish.json...
22:39:57 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Portuguese.json...
22:39:57 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Russian.json...
22:39:57 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Spanish.json...
22:39:57 [Macro Deck] [Info] >> LanguageManager: Loading $SuchByte.MacroDeck.Resources.Languages.Turkish.json...
22:39:57 [Macro Deck] [Info] >> Successfully read configuration file
22:39:57 [Macro Deck] [Info] >> Set language to Spanish
22:39:57 [Macro Deck] [Info] >> VariableManager: Initialize variables database...
22:39:57 [Macro Deck] [Info] >> VariableManager: 6 variables found
22:39:57 [Macro Deck] [Info] >> PluginManager: Loading plugins...
22:39:57 [Macro Deck] [Info] >> Loading plugin AutoHotkey Plugin
22:39:57 [Macro Deck] [Info] >> Loading plugin ShareX Plugin
22:39:57 [Macro Deck] [Info] >> Loading plugin Windows Utils
22:39:57 [Macro Deck] [Info] >> PluginManager: Enabling plugins...
22:39:57 [Macro Deck] [Info] >> AutoHotkey Plugin version 1.0.0 enabled (took 0ms)
22:39:57 [Macro Deck] [Info] >> ShareX Plugin version 1.1.1 enabled (took 13ms)
22:39:57 [Macro Deck] [Info] >> Windows Utils version 1.4.0 enabled (took 55ms)
22:39:57 [Macro Deck] [Info] >> Acción de botón version 2.12.0.221882003 enabled (took 0ms)
22:39:57 [Macro Deck] [Info] >> Variables de Macro Deck version 2.12.0.221882003 enabled (took 2ms)
22:39:57 [Macro Deck] [Info] >> Carpeta Macro Deck version 2.12.0.221882003 enabled (took 0ms)
22:39:57 [Macro Deck] [Info] >> Device version 2.12.0.221882003 enabled (took 0ms)
22:39:57 [Macro Deck] [Info] >> PluginManager: Plugins enabled
22:39:57 [Macro Deck] [Info] >> IconManager: Loading icon packs...
22:39:57 [Macro Deck] [Info] >> IconManager: Loaded 9 icon packs
22:39:57 [Macro Deck] [Info] >> ProfileManager: Loading profiles...
22:39:58 [Macro Deck] [Info] >> Loaded 2 profiles
22:39:58 [Macro Deck] [Info] >> Starting websocket server @ 192.190.0.153:8088
22:39:58 [Macro Deck] [Info] >> Starting USB websocket server @ 127.0.0.1:8088
22:39:58 [Macro Deck] [Info] >> Macro Deck started successfully
22:39:58 [Macro Deck] [Info] >> MacroDeckPipeServer: Initializing pipe server
22:39:58 [Macro Deck] [Info] >> MacroDeckPipeServer: Initializing pipe server complete
22:39:58 [Macro Deck] [Info] >> Macro Deck startup finished (took 1555ms)
22:40:43 [Macro Deck] [Error] >> MacroDeck: ApplicationThreadException: Field not found: 'SuchByte.MacroDeck.Variables.VariableManager.Variables'.
   at SuchByte.WindowsUtils.GUI.TextSelector.BtnAddVariable_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
22:40:56 [Macro Deck] [Error] >> MacroDeck: ApplicationThreadException: Field not found: 'SuchByte.MacroDeck.Variables.VariableManager.Variables'.
   at SuchByte.WindowsUtils.GUI.TextSelector.BtnAddVariable_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
22:41:02 [Macro Deck] [Info] >> Saved 2 profiles
22:44:16 [Macro Deck] [Error] >> MacroDeck: ApplicationThreadException: Field not found: 'SuchByte.MacroDeck.Variables.VariableManager.Variables'.
   at SuchByte.WindowsUtils.GUI.TextSelector.BtnAddVariable_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
22:47:36 [Macro Deck] [Info] >> Saved 2 profiles
22:47:36 [Macro Deck] [Info] >> Saved 2 profiles
22:49:52 [Macro Deck] [Error] >> MacroDeck: ApplicationThreadException: Field not found: 'SuchByte.MacroDeck.Variables.VariableManager.Variables'.
   at SuchByte.WindowsUtils.GUI.TextSelector.BtnAddVariable_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
22:49:53 [Macro Deck] [Error] >> MacroDeck: ApplicationThreadException: Field not found: 'SuchByte.MacroDeck.Variables.VariableManager.Variables'.
   at SuchByte.WindowsUtils.GUI.TextSelector.BtnAddVariable_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
22:49:53 [Macro Deck] [Error] >> MacroDeck: ApplicationThreadException: Field not found: 'SuchByte.MacroDeck.Variables.VariableManager.Variables'.
   at SuchByte.WindowsUtils.GUI.TextSelector.BtnAddVariable_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
22:54:23 [Macro Deck] [Info] >> Saved 2 profiles
22:54:23 [Macro Deck] [Info] >> Saved 2 profiles

**Comment by SuchByte** [comment]
Fixed with v1.4.1 of the plugin
